---
title: "Using fgsea package"
author: "Alexey Sergushichev"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using fgsea package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Loading necessary libraryries

```{r echo=F}
library(data.table)
library(fgsea)
```

File with the input data

```{r}
rnk.file <- system.file("extdata", "naive.vs.th1.rnk", package="fgsea")
gmt.file <- system.file("extdata", "mouse.reactome.gmt", package="fgsea")
```

Ranks

```{r}
ranks <- read.table(rnk.file,
                    header=T, colClasses = c("character", "numeric"))
ranks <- structure(ranks$t, names=ranks$ID)
str(ranks)
```

Pathways

```{r}
pathwayLines <- strsplit(readLines(gmt.file), "\t")
pathways <- lapply(pathwayLines, tail, -2)
names(pathways) <- sapply(pathwayLines, head, 1)
str(head(pathways))
```

## Running fgsea

Actual fgsea run

```{r}
set.seed(42)
system.time(
fgseaRes <- fgsea(pathways = pathways, 
                  stats = ranks,
                  minSize=15,
                  maxSize=500,
                  nperm=10000,
                  nproc=1)
)
head(fgseaRes[order(pval), ])
```

It tooks ten seconds to get results with significant hits after FDR correction:
```{r}
sum(fgseaRes[, padj < 0.01])
```
