// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// calcGseaStatCumulative
NumericVector calcGseaStatCumulative(NumericVector const& stats, int& n, int& k, double gseaParam);
RcppExport SEXP fgsea_calcGseaStatCumulative(SEXP statsSEXP, SEXP nSEXP, SEXP kSEXP, SEXP gseaParamSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector const& >::type stats(statsSEXP);
    Rcpp::traits::input_parameter< int& >::type n(nSEXP);
    Rcpp::traits::input_parameter< int& >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type gseaParam(gseaParamSEXP);
    rcpp_result_gen = Rcpp::wrap(calcGseaStatCumulative(stats, n, k, gseaParam));
    return rcpp_result_gen;
END_RCPP
}