# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calcGseaStatCumulativeParallel <- function(stats, n, k, gseaParam, m, pathwayScores, pathwaysSizes, iterations, seed) {
    .Call('fgsea_calcGseaStatCumulativeParallel', PACKAGE = 'fgsea', stats, n, k, gseaParam, m, pathwayScores, pathwaysSizes, iterations, seed)
}

